package action.rollCall.timeOffSearch;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletResponse;

public class ListMail {
	
	public void print(HttpServletResponse response, List <Map>list, String beginDate, String endDate) throws IOException{
			
			Date date=new Date();
			response.setContentType("text/html; charset=UTF-8");
			response.setContentType("application/vnd.ms-word");
			response.setHeader("Content-disposition","attachment;filename="+date.getTime()+".doc");
			
			PrintWriter out=response.getWriter();
			out.println ("<?xml version='1.0' encoding='UTF-8' standalone='yes'?>");
			out.println ("<?mso-application progid='Word.Document'?>");
			out.println ("<w:wordDocument xmlns:aml='http://schemas.microsoft.com/aml/2001/core' xmlns:wpc='http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas' xmlns:dt='uuid:C2F41010-65B3-11d1-A29F-00AA00C14882' xmlns:mc='http://schemas.openxmlformats.org/markup-compatibility/2006' xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:v='urn:schemas-microsoft-com:vml' xmlns:w10='urn:schemas-microsoft-com:office:word' xmlns:w='http://schemas.microsoft.com/office/word/2003/wordml' xmlns:wx='http://schemas.microsoft.com/office/word/2003/auxHint' xmlns:wne='http://schemas.microsoft.com/office/word/2006/wordml' xmlns:wsp='http://schemas.microsoft.com/office/word/2003/wordml/sp2' xmlns:sl='http://schemas.microsoft.com/schemaLibrary/2003/core' w:macrosPresent='no' w:embeddedObjPresent='no' w:ocxPresent='no' xml:space='preserve'>");
			out.println ("  <w:ignoreSubtree w:val='http://schemas.microsoft.com/office/word/2003/wordml/sp2'/>");
			out.println ("  <o:DocumentProperties>");
			out.println ("    <o:Author>John</o:Author>");
			out.println ("    <o:LastAuthor>John</o:LastAuthor>");
			out.println ("    <o:Revision>1</o:Revision>");
			out.println ("    <o:TotalTime>26</o:TotalTime>");
			out.println ("    <o:LastPrinted>2013-03-22T06:26:00Z</o:LastPrinted>");
			out.println ("    <o:Created>2013-03-22T06:11:00Z</o:Created>");
			out.println ("    <o:LastSaved>2013-03-22T06:38:00Z</o:LastSaved>");
			out.println ("    <o:Pages>1</o:Pages>");
			out.println ("    <o:Words>1</o:Words>");
			out.println ("    <o:Characters>6</o:Characters>");
			out.println ("    <o:Lines>1</o:Lines>");
			out.println ("    <o:Paragraphs>1</o:Paragraphs>");
			out.println ("    <o:CharactersWithSpaces>6</o:CharactersWithSpaces>");
			out.println ("    <o:Version>14</o:Version>");
			out.println ("  </o:DocumentProperties>");
			out.println ("  <w:fonts>");
			out.println ("    <w:defaultFonts w:ascii='Calibri' w:fareast='新細明體' w:h-ansi='Calibri' w:cs='Times New Roman'/>");
			out.println ("    <w:font w:name='Times New Roman'>");
			out.println ("      <w:panose-1 w:val='02020603050405020304'/>");
			out.println ("      <w:charset w:val='00'/>");
			out.println ("      <w:family w:val='Roman'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='E0002AFF' w:usb-1='C0007841' w:usb-2='00000009' w:usb-3='00000000' w:csb-0='000001FF' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("    <w:font w:name='SimSun'>");
			out.println ("      <w:altName w:val='宋体'/>");
			out.println ("      <w:panose-1 w:val='02010600030101010101'/>");
			out.println ("      <w:charset w:val='86'/>");
			out.println ("      <w:family w:val='auto'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='00000003' w:usb-1='288F0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00040001' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("    <w:font w:name='新細明體'>");
			out.println ("      <w:altName w:val='PMingLiU'/>");
			out.println ("      <w:panose-1 w:val='02020500000000000000'/>");
			out.println ("      <w:charset w:val='88'/>");
			out.println ("      <w:family w:val='Roman'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='A00002FF' w:usb-1='28CFFCFA' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("    <w:font w:name='新細明體'>");
			out.println ("      <w:altName w:val='PMingLiU'/>");
			out.println ("      <w:panose-1 w:val='02020500000000000000'/>");
			out.println ("      <w:charset w:val='88'/>");
			out.println ("      <w:family w:val='Roman'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='A00002FF' w:usb-1='28CFFCFA' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("    <w:font w:name='Cambria'>");
			out.println ("      <w:panose-1 w:val='02040503050406030204'/>");
			out.println ("      <w:charset w:val='00'/>");
			out.println ("      <w:family w:val='Roman'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='E00002FF' w:usb-1='400004FF' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='0000019F' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("    <w:font w:name='Calibri'>");
			out.println ("      <w:panose-1 w:val='020F0502020204030204'/>");
			out.println ("      <w:charset w:val='00'/>");
			out.println ("      <w:family w:val='Swiss'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='E00002FF' w:usb-1='4000ACFF' w:usb-2='00000001' w:usb-3='00000000' w:csb-0='0000019F' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("    <w:font w:name='Trebuchet MS'>");
			out.println ("      <w:panose-1 w:val='020B0603020202020204'/>");
			out.println ("      <w:charset w:val='00'/>");
			out.println ("      <w:family w:val='Swiss'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='00000287' w:usb-1='00000000' w:usb-2='00000000' w:usb-3='00000000' w:csb-0='0000009F' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("    <w:font w:name='@新細明體'>");
			out.println ("      <w:panose-1 w:val='02020500000000000000'/>");
			out.println ("      <w:charset w:val='88'/>");
			out.println ("      <w:family w:val='Roman'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='A00002FF' w:usb-1='28CFFCFA' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00100001' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("    <w:font w:name='@SimSun'>");
			out.println ("      <w:panose-1 w:val='02010600030101010101'/>");
			out.println ("      <w:charset w:val='86'/>");
			out.println ("      <w:family w:val='auto'/>");
			out.println ("      <w:pitch w:val='variable'/>");
			out.println ("      <w:sig w:usb-0='00000003' w:usb-1='288F0000' w:usb-2='00000016' w:usb-3='00000000' w:csb-0='00040001' w:csb-1='00000000'/>");
			out.println ("    </w:font>");
			out.println ("  </w:fonts>");
			out.println ("  <w:styles>");
			out.println ("    <w:versionOfBuiltInStylenames w:val='7'/>");
			out.println ("    <w:latentStyles w:defLockedState='off' w:latentStyleCount='267'>");
			out.println ("      <w:lsdException w:name='Normal'/>");
			out.println ("      <w:lsdException w:name='heading 1'/>");
			out.println ("      <w:lsdException w:name='heading 2'/>");
			out.println ("      <w:lsdException w:name='heading 3'/>");
			out.println ("      <w:lsdException w:name='heading 4'/>");
			out.println ("      <w:lsdException w:name='heading 5'/>");
			out.println ("      <w:lsdException w:name='heading 6'/>");
			out.println ("      <w:lsdException w:name='heading 7'/>");
			out.println ("      <w:lsdException w:name='heading 8'/>");
			out.println ("      <w:lsdException w:name='heading 9'/>");
			out.println ("      <w:lsdException w:name='toc 1'/>");
			out.println ("      <w:lsdException w:name='toc 2'/>");
			out.println ("      <w:lsdException w:name='toc 3'/>");
			out.println ("      <w:lsdException w:name='toc 4'/>");
			out.println ("      <w:lsdException w:name='toc 5'/>");
			out.println ("      <w:lsdException w:name='toc 6'/>");
			out.println ("      <w:lsdException w:name='toc 7'/>");
			out.println ("      <w:lsdException w:name='toc 8'/>");
			out.println ("      <w:lsdException w:name='toc 9'/>");
			out.println ("      <w:lsdException w:name='caption'/>");
			out.println ("      <w:lsdException w:name='Title'/>");
			out.println ("      <w:lsdException w:name='Default Paragraph Font'/>");
			out.println ("      <w:lsdException w:name='Subtitle'/>");
			out.println ("      <w:lsdException w:name='Strong'/>");
			out.println ("      <w:lsdException w:name='Emphasis'/>");
			out.println ("      <w:lsdException w:name='Table Grid'/>");
			out.println ("      <w:lsdException w:name='Placeholder Text'/>");
			out.println ("      <w:lsdException w:name='No Spacing'/>");
			out.println ("      <w:lsdException w:name='Light Shading'/>");
			out.println ("      <w:lsdException w:name='Light List'/>");
			out.println ("      <w:lsdException w:name='Light Grid'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 1'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 2'/>");
			out.println ("      <w:lsdException w:name='Medium List 1'/>");
			out.println ("      <w:lsdException w:name='Medium List 2'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 1'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 2'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 3'/>");
			out.println ("      <w:lsdException w:name='Dark List'/>");
			out.println ("      <w:lsdException w:name='Colorful Shading'/>");
			out.println ("      <w:lsdException w:name='Colorful List'/>");
			out.println ("      <w:lsdException w:name='Colorful Grid'/>");
			out.println ("      <w:lsdException w:name='Light Shading Accent 1'/>");
			out.println ("      <w:lsdException w:name='Light List Accent 1'/>");
			out.println ("      <w:lsdException w:name='Light Grid Accent 1'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 1'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 1'/>");
			out.println ("      <w:lsdException w:name='Medium List 1 Accent 1'/>");
			out.println ("      <w:lsdException w:name='Revision'/>");
			out.println ("      <w:lsdException w:name='List Paragraph'/>");
			out.println ("      <w:lsdException w:name='Quote'/>");
			out.println ("      <w:lsdException w:name='Intense Quote'/>");
			out.println ("      <w:lsdException w:name='Medium List 2 Accent 1'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 1'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 1'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 1'/>");
			out.println ("      <w:lsdException w:name='Dark List Accent 1'/>");
			out.println ("      <w:lsdException w:name='Colorful Shading Accent 1'/>");
			out.println ("      <w:lsdException w:name='Colorful List Accent 1'/>");
			out.println ("      <w:lsdException w:name='Colorful Grid Accent 1'/>");
			out.println ("      <w:lsdException w:name='Light Shading Accent 2'/>");
			out.println ("      <w:lsdException w:name='Light List Accent 2'/>");
			out.println ("      <w:lsdException w:name='Light Grid Accent 2'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 2'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 2'/>");
			out.println ("      <w:lsdException w:name='Medium List 1 Accent 2'/>");
			out.println ("      <w:lsdException w:name='Medium List 2 Accent 2'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 2'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 2'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 2'/>");
			out.println ("      <w:lsdException w:name='Dark List Accent 2'/>");
			out.println ("      <w:lsdException w:name='Colorful Shading Accent 2'/>");
			out.println ("      <w:lsdException w:name='Colorful List Accent 2'/>");
			out.println ("      <w:lsdException w:name='Colorful Grid Accent 2'/>");
			out.println ("      <w:lsdException w:name='Light Shading Accent 3'/>");
			out.println ("      <w:lsdException w:name='Light List Accent 3'/>");
			out.println ("      <w:lsdException w:name='Light Grid Accent 3'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 3'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 3'/>");
			out.println ("      <w:lsdException w:name='Medium List 1 Accent 3'/>");
			out.println ("      <w:lsdException w:name='Medium List 2 Accent 3'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 3'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 3'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 3'/>");
			out.println ("      <w:lsdException w:name='Dark List Accent 3'/>");
			out.println ("      <w:lsdException w:name='Colorful Shading Accent 3'/>");
			out.println ("      <w:lsdException w:name='Colorful List Accent 3'/>");
			out.println ("      <w:lsdException w:name='Colorful Grid Accent 3'/>");
			out.println ("      <w:lsdException w:name='Light Shading Accent 4'/>");
			out.println ("      <w:lsdException w:name='Light List Accent 4'/>");
			out.println ("      <w:lsdException w:name='Light Grid Accent 4'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 4'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 4'/>");
			out.println ("      <w:lsdException w:name='Medium List 1 Accent 4'/>");
			out.println ("      <w:lsdException w:name='Medium List 2 Accent 4'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 4'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 4'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 4'/>");
			out.println ("      <w:lsdException w:name='Dark List Accent 4'/>");
			out.println ("      <w:lsdException w:name='Colorful Shading Accent 4'/>");
			out.println ("      <w:lsdException w:name='Colorful List Accent 4'/>");
			out.println ("      <w:lsdException w:name='Colorful Grid Accent 4'/>");
			out.println ("      <w:lsdException w:name='Light Shading Accent 5'/>");
			out.println ("      <w:lsdException w:name='Light List Accent 5'/>");
			out.println ("      <w:lsdException w:name='Light Grid Accent 5'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 5'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 5'/>");
			out.println ("      <w:lsdException w:name='Medium List 1 Accent 5'/>");
			out.println ("      <w:lsdException w:name='Medium List 2 Accent 5'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 5'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 5'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 5'/>");
			out.println ("      <w:lsdException w:name='Dark List Accent 5'/>");
			out.println ("      <w:lsdException w:name='Colorful Shading Accent 5'/>");
			out.println ("      <w:lsdException w:name='Colorful List Accent 5'/>");
			out.println ("      <w:lsdException w:name='Colorful Grid Accent 5'/>");
			out.println ("      <w:lsdException w:name='Light Shading Accent 6'/>");
			out.println ("      <w:lsdException w:name='Light List Accent 6'/>");
			out.println ("      <w:lsdException w:name='Light Grid Accent 6'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 1 Accent 6'/>");
			out.println ("      <w:lsdException w:name='Medium Shading 2 Accent 6'/>");
			out.println ("      <w:lsdException w:name='Medium List 1 Accent 6'/>");
			out.println ("      <w:lsdException w:name='Medium List 2 Accent 6'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 1 Accent 6'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 2 Accent 6'/>");
			out.println ("      <w:lsdException w:name='Medium Grid 3 Accent 6'/>");
			out.println ("      <w:lsdException w:name='Dark List Accent 6'/>");
			out.println ("      <w:lsdException w:name='Colorful Shading Accent 6'/>");
			out.println ("      <w:lsdException w:name='Colorful List Accent 6'/>");
			out.println ("      <w:lsdException w:name='Colorful Grid Accent 6'/>");
			out.println ("      <w:lsdException w:name='Subtle Emphasis'/>");
			out.println ("      <w:lsdException w:name='Intense Emphasis'/>");
			out.println ("      <w:lsdException w:name='Subtle Reference'/>");
			out.println ("      <w:lsdException w:name='Intense Reference'/>");
			out.println ("      <w:lsdException w:name='Book Title'/>");
			out.println ("      <w:lsdException w:name='Bibliography'/>");
			out.println ("      <w:lsdException w:name='TOC Heading'/>");
			out.println ("    </w:latentStyles>");
			out.println ("    <w:style w:type='paragraph' w:default='on' w:styleId='a'>");
			out.println ("      <w:name w:val='Normal'/>");
			out.println ("      <wx:uiName wx:val='內文'/>");
			out.println ("      <w:pPr>");
			out.println ("        <w:widowControl w:val='off'/>");
			out.println ("      </w:pPr>");
			out.println ("      <w:rPr>");
			out.println ("        <wx:font wx:val='Calibri'/>");
			out.println ("        <w:kern w:val='2'/>");
			out.println ("        <w:sz w:val='24'/>");
			out.println ("        <w:sz-cs w:val='22'/>");
			out.println ("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
			out.println ("      </w:rPr>");
			out.println ("    </w:style>");
			out.println ("    <w:style w:type='character' w:default='on' w:styleId='a0'>");
			out.println ("      <w:name w:val='Default Paragraph Font'/>");
			out.println ("      <wx:uiName wx:val='預設段落字型'/>");
			out.println ("    </w:style>");
			out.println ("    <w:style w:type='table' w:default='on' w:styleId='a1'>");
			out.println ("      <w:name w:val='Normal Table'/>");
			out.println ("      <wx:uiName wx:val='表格內文'/>");
			out.println ("      <w:rPr>");
			out.println ("        <wx:font wx:val='Calibri'/>");
			out.println ("        <w:lang w:val='EN-US' w:fareast='ZH-TW' w:bidi='AR-SA'/>");
			out.println ("      </w:rPr>");
			out.println ("      <w:tblPr>");
			out.println ("        <w:tblInd w:w='0' w:type='dxa'/>");
			out.println ("        <w:tblCellMar>");
			out.println ("          <w:top w:w='0' w:type='dxa'/>");
			out.println ("          <w:left w:w='108' w:type='dxa'/>");
			out.println ("          <w:bottom w:w='0' w:type='dxa'/>");
			out.println ("          <w:right w:w='108' w:type='dxa'/>");
			out.println ("        </w:tblCellMar>");
			out.println ("      </w:tblPr>");
			out.println ("    </w:style>");
			out.println ("    <w:style w:type='list' w:default='on' w:styleId='a2'>");
			out.println ("      <w:name w:val='No List'/>");
			out.println ("      <wx:uiName wx:val='無清單'/>");
			out.println ("    </w:style>");
			out.println ("    <w:style w:type='paragraph' w:styleId='Address1'>");
			out.println ("      <w:name w:val='Address 1'/>");
			out.println ("      <w:basedOn w:val='a'/>");
			out.println ("      <w:rsid w:val='00C854CA'/>");
			out.println ("      <w:pPr>");
			out.println ("        <w:widowControl/>");
			out.println ("        <w:spacing w:line='240' w:line-rule='at-least'/>");
			out.println ("      </w:pPr>");
			out.println ("      <w:rPr>");
			out.println ("        <w:rFonts w:ascii='Trebuchet MS' w:fareast='SimSun' w:h-ansi='Trebuchet MS'/>");
			out.println ("        <wx:font wx:val='Trebuchet MS'/>");
			out.println ("        <w:kern w:val='0'/>");
			out.println ("        <w:sz w:val='20'/>");
			out.println ("        <w:sz-cs w:val='24'/>");
			out.println ("        <w:lang w:fareast='ZH-CN'/>");
			out.println ("      </w:rPr>");
			out.println ("    </w:style>");
			out.println ("    <w:style w:type='paragraph' w:styleId='Address2'>");
			out.println ("      <w:name w:val='Address 2'/>");
			out.println ("      <w:basedOn w:val='a'/>");
			out.println ("      <w:rsid w:val='00C854CA'/>");
			out.println ("      <w:pPr>");
			out.println ("        <w:widowControl/>");
			out.println ("        <w:spacing w:line='280' w:line-rule='at-least'/>");
			out.println ("      </w:pPr>");
			out.println ("      <w:rPr>");
			out.println ("        <w:rFonts w:ascii='Trebuchet MS' w:fareast='SimSun' w:h-ansi='Trebuchet MS'/>");
			out.println ("        <wx:font wx:val='Trebuchet MS'/>");
			out.println ("        <w:b/>");
			out.println ("        <w:caps/>");
			out.println ("        <w:kern w:val='0'/>");
			out.println ("        <w:sz w:val='20'/>");
			out.println ("        <w:sz-cs w:val='24'/>");
			out.println ("        <w:lang w:fareast='ZH-CN'/>");
			out.println ("      </w:rPr>");
			out.println ("    </w:style>");
			out.println ("    <w:style w:type='paragraph' w:styleId='a3'>");
			out.println ("      <w:name w:val='Balloon Text'/>");
			out.println ("      <wx:uiName wx:val='註解方塊文字'/>");
			out.println ("      <w:basedOn w:val='a'/>");
			out.println ("      <w:link w:val='a4'/>");
			out.println ("      <w:rsid w:val='00C854CA'/>");
			out.println ("      <w:rPr>");
			out.println ("        <w:rFonts w:ascii='Cambria' w:h-ansi='Cambria'/>");
			out.println ("        <wx:font wx:val='Cambria'/>");
			out.println ("        <w:sz w:val='18'/>");
			out.println ("        <w:sz-cs w:val='18'/>");
			out.println ("      </w:rPr>");
			out.println ("    </w:style>");
			out.println ("    <w:style w:type='character' w:styleId='a4'>");
			out.println ("      <w:name w:val='註解方塊文字 字元'/>");
			out.println ("      <w:link w:val='a3'/>");
			out.println ("      <w:rsid w:val='00C854CA'/>");
			out.println ("      <w:rPr>");
			out.println ("        <w:rFonts w:ascii='Cambria' w:fareast='新細明體' w:h-ansi='Cambria' w:cs='Times New Roman'/>");
			out.println ("        <w:sz w:val='18'/>");
			out.println ("        <w:sz-cs w:val='18'/>");
			out.println ("      </w:rPr>");
			out.println ("    </w:style>");
			out.println ("  </w:styles>");
			out.println ("  <w:shapeDefaults>");
			out.println ("    <o:shapedefaults v:ext='edit' spidmax='1033'/>");
			out.println ("    <o:shapelayout v:ext='edit'>");
			out.println ("      <o:idmap v:ext='edit' data='1'/>");
			out.println ("    </o:shapelayout>");
			out.println ("  </w:shapeDefaults>");
			out.println ("  <w:docPr>");
			out.println ("    <w:view w:val='print'/>");
			out.println ("    <w:zoom w:percent='100'/>");
			out.println ("    <w:doNotEmbedSystemFonts/>");
			out.println ("    <w:bordersDontSurroundHeader/>");
			out.println ("    <w:bordersDontSurroundFooter/>");
			out.println ("    <w:defaultTabStop w:val='480'/>");
			out.println ("    <w:displayHorizontalDrawingGridEvery w:val='0'/>");
			out.println ("    <w:displayVerticalDrawingGridEvery w:val='2'/>");
			out.println ("    <w:punctuationKerning/>");
			out.println ("    <w:characterSpacingControl w:val='CompressPunctuation'/>");
			out.println ("    <w:optimizeForBrowser/>");
			out.println ("    <w:allowPNG/>");
			out.println ("    <w:validateAgainstSchema/>");
			out.println ("    <w:saveInvalidXML w:val='off'/>");
			out.println ("    <w:ignoreMixedContent w:val='off'/>");
			out.println ("    <w:alwaysShowPlaceholderText w:val='off'/>");
			out.println ("    <w:compat>");
			out.println ("      <w:spaceForUL/>");
			out.println ("      <w:balanceSingleByteDoubleByteWidth/>");
			out.println ("      <w:doNotLeaveBackslashAlone/>");
			out.println ("      <w:ulTrailSpace/>");
			out.println ("      <w:doNotExpandShiftReturn/>");
			out.println ("      <w:adjustLineHeightInTable/>");
			out.println ("      <w:breakWrappedTables/>");
			out.println ("      <w:snapToGridInCell/>");
			out.println ("      <w:wrapTextWithPunct/>");
			out.println ("      <w:useAsianBreakRules/>");
			out.println ("      <w:dontGrowAutofit/>");
			out.println ("      <w:useFELayout/>");
			out.println ("    </w:compat>");
			out.println ("    <wsp:rsids>");
			out.println ("      <wsp:rsidRoot wsp:val='00C854CA'/>");
			out.println ("      <wsp:rsid wsp:val='00042234'/>");
			out.println ("      <wsp:rsid wsp:val='007340CD'/>");
			out.println ("      <wsp:rsid wsp:val='007A476C'/>");
			out.println ("      <wsp:rsid wsp:val='009B15AD'/>");
			out.println ("      <wsp:rsid wsp:val='00A873D1'/>");
			out.println ("      <wsp:rsid wsp:val='00C854CA'/>");
			out.println ("    </wsp:rsids>");
			out.println ("  </w:docPr>");
			out.println ("  <w:body>");
			out.println ("    <wx:sect>");
			
			List tmp;
			int cnt;
			StringBuilder sb;
			for(int i=0; i<list.size(); i++){			
				out.println ("      <w:p wsp:rsidR='007A476C' wsp:rsidRPr='00C854CA' wsp:rsidRDefault='00A873D1'>");
				out.println ("        <w:r>");
				out.println ("          <w:rPr>");
				out.println ("            <w:noProof/>");
				out.println ("          </w:rPr>");
				out.println ("          <w:pict>");
				out.println ("            <v:shapetype id='_x0000_t202' coordsize='21600,21600' o:spt='202' path='m,l,21600r21600,l21600,xe'>");
				out.println ("              <v:stroke joinstyle='miter'/>");
				out.println ("              <v:path gradientshapeok='t' o:connecttype='rect'/>");
				out.println ("            </v:shapetype>");
				out.println ("            <v:shape id='文字方塊 11' o:spid='_x0000_s1032' type='#_x0000_t202' style='position:absolute;margin-left:312pt;margin-top:66.75pt;width:120pt;height:23.25pt;z-index:6;visibility:visible;mso-wrap-style:square;mso-width-percent:0;mso-height-percent:0;mso-wrap-distance-left:9pt;mso-wrap-distance-top:0;mso-wrap-distance-right:9pt;mso-wrap-distance-bottom:0;mso-position-horizontal:absolute;mso-position-horizontal-relative:text;mso-position-vertical:absolute;mso-position-vertical-relative:text;mso-width-percent:0;mso-height-percent:0;mso-width-relative:margin;mso-height-relative:margin;v-text-anchor:top' o:gfxdata='UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF&#xA;90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA&#xA;0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD&#xA;OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893&#xA;SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y&#xA;JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl&#xA;bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR&#xA;JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY&#xA;22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i&#xA;OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA&#xA;IQAUREv/aAIAAKUEAAAOAAAAZHJzL2Uyb0RvYy54bWysVF1uEzEQfkfiDpbf6W5C0tKomyq0CkKq&#xA;aKUW9dnxepuVvB5jO9kNF0DiAOWZA3AADtSeg8/epC2FJ0QenPnzjOebb/bouGs0WyvnazIFH+zl&#xA;nCkjqazNTcE/Xs1fveHMB2FKocmogm+U58fTly+OWjtRQ1qSLpVjSGL8pLUFX4ZgJ1nm5VI1wu+R&#xA;VQbOilwjAlR3k5VOtMje6GyY5/tZS660jqTyHtbT3smnKX9VKRnOq8qrwHTB8baQTpfORTyz6ZGY&#xA;3Dhhl7XcPkP8wysaURsUfUh1KoJgK1f/kaqppSNPVdiT1GRUVbVUqQd0M8ifdXO5FFalXgCOtw8w&#xA;+f+XVn5YXzhWl5jdgDMjGszo/vbL3Y9v97c/775/ZTADo9b6CUIvLYJD95Y6xO/sHsbYele5Jv6j&#xA;KQY/0N48IKy6wGS8NB6O8hwuCd/wcDw8GMc02eNt63x4p6hhUSi4wwQTsGJ95kMfuguJxTzpupzX&#xA;Widl40+0Y2uBYYMjJbWcaeEDjAWfp9+22m/XtGFtwfdfj/NUyVDM15fSJuZViUjb+hGKvuUohW7R&#xA;JfhSH9GyoHIDlBz1XPNWzmu0coZ3XAgHcqF7LEw4x1FpQmXaSpwtyX3+mz3GY+bwctaCrAX3n1bC&#xA;KbT33oANh4PRKLI7KaPxwRCKe+pZPPWYVXNCgAgDx+uSGOOD3omVo+YaezWLVeESRqJ2wcNOPAn9&#xA;CmEvpZrNUhD4bEU4M5dWxtQRtzioq+5aOLudZgAPPtCO1mLybKh9bLxpaLYKVNVp4o+ogilRwS4k&#xA;zmz3Ni7bUz1FPX5dpr8AAAD//wMAUEsDBBQABgAIAAAAIQCtgrlg3QAAAAsBAAAPAAAAZHJzL2Rv&#xA;d25yZXYueG1sTI/NTsMwEITvSLyDtUjcqN0foijEqRASVyTa0rMbL3GEvY5it0379GxPcNyZ0ew3&#xA;9XoKXpxwTH0kDfOZAoHURttTp2G3fX8qQaRsyBofCTVcMMG6ub+rTWXjmT7xtMmd4BJKldHgch4q&#xA;KVPrMJg0iwMSe99xDCbzOXbSjubM5cHLhVKFDKYn/uDMgG8O25/NMWjYd+G6/5oPo7PBr+jjetnu&#xA;Yq/148P0+gIi45T/wnDDZ3RomOkQj2ST8BqKxYq3ZDaWy2cQnCiLm3JgpVQKZFPL/xuaXwAAAP//&#xA;AwBQSwECLQAUAAYACAAAACEAtoM4kv4AAADhAQAAEwAAAAAAAAAAAAAAAAAAAAAAW0NvbnRlbnRf&#xA;VHlwZXNdLnhtbFBLAQItABQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAAAAAAAAAAAAAAC8BAABf&#xA;cmVscy8ucmVsc1BLAQItABQABgAIAAAAIQAUREv/aAIAAKUEAAAOAAAAAAAAAAAAAAAAAC4CAABk&#xA;cnMvZTJvRG9jLnhtbFBLAQItABQABgAIAAAAIQCtgrlg3QAAAAsBAAAPAAAAAAAAAAAAAAAAAMIE&#xA;AABkcnMvZG93bnJldi54bWxQSwUGAAAAAAQABADzAAAAzAUAAAAA&#xA;' stroked='f' strokeweight='.5pt'>");
				out.println ("              <v:textbox>");
				out.println ("                <w:txbxContent>");
				out.println ("                  <w:p wsp:rsidR='009B15AD' wsp:rsidRDefault='009B15AD' wsp:rsidP='009B15AD'>");
				out.println ("                    <w:pPr>");
				out.println ("                      <w:jc w:val='center'/>");
				out.println ("                    </w:pPr>");
				out.println ("                    <w:r>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>(</w:t>");
				out.println ("                    </w:r>");
				out.println ("                    <w:r>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>掛號</w:t>");
				out.println ("                    </w:r>");
				out.println ("                    <w:r>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>)</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                </w:txbxContent>");
				out.println ("              </v:textbox>");
				out.println ("            </v:shape>");
				out.println ("          </w:pict>");
				out.println ("        </w:r>");
				out.println ("        <w:r>");
				out.println ("          <w:rPr>");
				out.println ("            <w:noProof/>");
				out.println ("          </w:rPr>");
				out.println ("          <w:pict>");
				out.println ("            <v:shape id='文字方塊 9' o:spid='_x0000_s1031' type='#_x0000_t202' style='position:absolute;margin-left:-66pt;margin-top:258.75pt;width:549pt;height:438.75pt;z-index:5;visibility:visible;mso-wrap-style:square;mso-wrap-distance-left:9pt;mso-wrap-distance-top:0;mso-wrap-distance-right:9pt;mso-wrap-distance-bottom:0;mso-position-horizontal:absolute;mso-position-horizontal-relative:text;mso-position-vertical:absolute;mso-position-vertical-relative:text;v-text-anchor:top' o:gfxdata='UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF&#xA;90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA&#xA;0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD&#xA;OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893&#xA;SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y&#xA;JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl&#xA;bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR&#xA;JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY&#xA;22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i&#xA;OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA&#xA;IQCFnep4agIAAKQEAAAOAAAAZHJzL2Uyb0RvYy54bWysVF1OGzEQfq/UO1h+L5uEBJqIDUpBqSoh&#xA;QIKKZ8frJSt5Pa7tZDe9QKUegD73AD1ADwTn6GdvApT2qWoenPnzjOebb/bouK01WyvnKzI57+/1&#xA;OFNGUlGZ25x/vJ6/ecuZD8IUQpNROd8oz4+nr18dNXaiBrQkXSjHkMT4SWNzvgzBTrLMy6Wqhd8j&#xA;qwycJblaBKjuNiucaJC91tmg1zvIGnKFdSSV97Cedk4+TfnLUslwUZZeBaZzjreFdLp0LuKZTY/E&#xA;5NYJu6zk9hniH15Ri8qg6GOqUxEEW7nqj1R1JR15KsOepDqjsqykSj2gm37vRTdXS2FV6gXgePsI&#xA;k/9/aeX5+tKxqsj5mDMjaozo4e7L/Y9vD3c/779/ZeOIUGP9BIFXFqGhfUctJr2zexhj423p6viP&#xA;lhj8wHrziK9qA5MwHowPB/s9uCR8o9HhoD8YxTzZ03XrfHivqGZRyLnDABOuYn3mQxe6C4nVPOmq&#xA;mFdaJ2XjT7Rja4FZgyIFNZxp4QOMOZ+n37bab9e0YQ3etj/qpUqGYr6ulDYxr0o82taPWHQ9Rym0&#xA;izahN9zhsaBiA5gcdVTzVs4rtHKGd1wKB26hfexLuMBRakJl2kqcLcl9/ps9xmPk8HLWgKs5959W&#xA;wim098GADOP+cBjJnZQhcIXinnsWzz1mVZ8QIOpjM61MYowPeieWjuobrNUsVoVLGInaOQ878SR0&#xA;G4S1lGo2S0GgsxXhzFxZGVNH3OKgrtsb4ex2mgFEOKcdq8XkxVC72HjT0GwVqKzSxCPOHapgSlSw&#xA;Cokz27WNu/ZcT1FPH5fpLwAAAP//AwBQSwMEFAAGAAgAAAAhAMGjirLgAAAADQEAAA8AAABkcnMv&#xA;ZG93bnJldi54bWxMj8FOwzAMhu9IvENkJG5b2o0WVppOCIkrEtvYOWtMU5E4VZNt3Z4ec4Kj7U+/&#xA;v79eT96JE46xD6Qgn2cgkNpgeuoU7LZvsycQMWky2gVCBReMsG5ub2pdmXCmDzxtUic4hGKlFdiU&#xA;hkrK2Fr0Os7DgMS3rzB6nXgcO2lGfeZw7+Qiy0rpdU/8weoBXy2235ujV7Dv/HX/mQ+jNd490Pv1&#xA;st2FXqn7u+nlGUTCKf3B8KvP6tCw0yEcyUThFMzy5YLLJAVF/liAYGRVlrw5MLtcFRnIppb/WzQ/&#xA;AAAA//8DAFBLAQItABQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAAAAAAAAAAAAAAAAAAABbQ29u&#xA;dGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhADj9If/WAAAAlAEAAAsAAAAAAAAAAAAAAAAA&#xA;LwEAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAIWd6nhqAgAApAQAAA4AAAAAAAAAAAAAAAAA&#xA;LgIAAGRycy9lMm9Eb2MueG1sUEsBAi0AFAAGAAgAAAAhAMGjirLgAAAADQEAAA8AAAAAAAAAAAAA&#xA;AAAAxAQAAGRycy9kb3ducmV2LnhtbFBLBQYAAAAABAAEAPMAAADRBQAAAAA=&#xA;' stroked='f' strokeweight='.5pt'>");
				out.println ("              <v:textbox>");
				out.println ("                <w:txbxContent>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:lang w:val='ZH-HK'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>貴子弟 "+list.get(i).get("student_name")+" 就讀本校 "+list.get(i).get("ClassName")+" 學號  "+list.get(i).get("student_no")+"</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>截至"+endDate+"累計曠課"+list.get(i).get("endCnt")+"節，請督促其勿再曠課，以免影響操行成績。</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>貴子弟缺曠紀錄如下</w:t>");
				out.println ("                    </w:r>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>:</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t></w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				
				tmp=(List)list.get(i).get("dilgs");
					
				cnt=0;
				for(int j=0; j<15; j++){
					
					sb=new StringBuilder();
					for(int k=0; k<6; k++){
						if(cnt<tmp.size()){
							sb.append(    ((Map)tmp.get(cnt)).get("date")+"第"+((Map)tmp.get(cnt)).get("cls")+"節, "            );
							cnt++;
						}else{
							sb.append("");
							//cnt++;
						}						
					}					
					
					out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
					out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
					out.println ("                      <w:rPr>");
					out.println ("                        <w:rFonts w:hint='fareast'/>");
					out.println ("                      </w:rPr>");
					out.println ("                      <w:t>"+sb+"</w:t>");
					out.println ("                    </w:r>");
					out.println ("                  </w:p>");					
				}
				
				
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t></w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				
				
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>此致貴家長</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t></w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>註1:曠課每節扣操行0.5分</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>註2:按教育部規定曠課達45節勒令退學</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='00C854CA' wsp:rsidRDefault='00C854CA'/>");
				out.println ("                </w:txbxContent>");
				out.println ("              </v:textbox>");
				out.println ("            </v:shape>");
				out.println ("          </w:pict>");
				out.println ("        </w:r>");
				out.println ("        <w:r>");
				out.println ("          <w:rPr>");
				out.println ("            <w:noProof/>");
				out.println ("          </w:rPr>");
				out.println ("          <w:pict>");
				out.println ("            <v:shape id='文字方塊 8' o:spid='_x0000_s1030' type='#_x0000_t202' style='position:absolute;margin-left:1.5pt;margin-top:152.25pt;width:474pt;height:1in;z-index:4;visibility:visible;mso-wrap-style:square;mso-height-percent:0;mso-wrap-distance-left:9pt;mso-wrap-distance-top:0;mso-wrap-distance-right:9pt;mso-wrap-distance-bottom:0;mso-position-horizontal:absolute;mso-position-horizontal-relative:text;mso-position-vertical:absolute;mso-position-vertical-relative:text;mso-height-percent:0;mso-height-relative:margin;v-text-anchor:top' o:gfxdata='UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF&#xA;90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA&#xA;0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD&#xA;OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893&#xA;SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y&#xA;JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl&#xA;bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR&#xA;JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY&#xA;22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i&#xA;OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA&#xA;IQA4wYKjZwIAAKMEAAAOAAAAZHJzL2Uyb0RvYy54bWysVEtu2zAQ3RfoHQjuG8n5NTEiB24CFwWC&#xA;JEBSZE1TlC2A4rAkbcm9QIEeIF33AD1AD5Sco4+UnbhpV0W9oOfHGc6bNzo57RrNlsr5mkzBBzs5&#xA;Z8pIKmszK/jH28mbI858EKYUmowq+Ep5fjp6/eqktUO1S3PSpXIMSYwftrbg8xDsMMu8nKtG+B2y&#xA;ysBZkWtEgOpmWelEi+yNznbz/DBryZXWkVTew3reO/ko5a8qJcNVVXkVmC443hbS6dI5jWc2OhHD&#xA;mRN2Xsv1M8Q/vKIRtUHRp1TnIgi2cPUfqZpaOvJUhR1JTUZVVUuVekA3g/xFNzdzYVXqBeB4+wST&#xA;/39p5eXy2rG6LDgGZUSDET3ef3n48e3x/ufD96/sKCLUWj9E4I1FaOjeUYdJb+wexth4V7km/qMl&#xA;Bj+wXj3hq7rAJIyH+eD4KIdLwnc82N+HjPTZ823rfHivqGFRKLjD/BKsYnnhQx+6CYnFPOm6nNRa&#xA;J2Xlz7RjS4FRgyEltZxp4QOMBZ+k37rab9e0YS2etneQp0qGYr6+lDYxr0o0WtePUPQtRyl00y6B&#xA;t7eBY0rlCig56pnmrZzUaOUC77gWDtRC91iXcIWj0oTKtJY4m5P7/Dd7jMfE4eWsBVUL7j8thFNo&#xA;74MBFxKS4HZS9g/e7qKG2/ZMtz1m0ZwRIBpgMa1MYowPeiNWjpo7bNU4VoVLGInaBQ8b8Sz0C4St&#xA;lGo8TkFgsxXhwtxYGVNH3OKgbrs74ex6mgE8uKQNqcXwxVD72HjT0HgRqKrTxCPOPapgSlSwCYkz&#xA;662Nq7atp6jnb8voFwAAAP//AwBQSwMEFAAGAAgAAAAhANhPNfjcAAAACQEAAA8AAABkcnMvZG93&#xA;bnJldi54bWxMj81OwzAQhO9IvIO1SNyoE0hQCXEqhMQVqb9nN17iCHsdxW6b9um7PcFptTuj2W/q&#xA;xeSdOOIY+0AK8lkGAqkNpqdOwWb99TQHEZMmo10gVHDGCIvm/q7WlQknWuJxlTrBIRQrrcCmNFRS&#xA;xtai13EWBiTWfsLodeJ17KQZ9YnDvZPPWfYqve6JP1g94KfF9nd18Ap2nb/stvkwWuNdQd+X83oT&#xA;eqUeH6aPdxAJp/Rnhhs+o0PDTPtwIBOFU/DCTdJtFCUI1t/KnC97BUUxL0E2tfzfoLkCAAD//wMA&#xA;UEsBAi0AFAAGAAgAAAAhALaDOJL+AAAA4QEAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5&#xA;cGVzXS54bWxQSwECLQAUAAYACAAAACEAOP0h/9YAAACUAQAACwAAAAAAAAAAAAAAAAAvAQAAX3Jl&#xA;bHMvLnJlbHNQSwECLQAUAAYACAAAACEAOMGCo2cCAACjBAAADgAAAAAAAAAAAAAAAAAuAgAAZHJz&#xA;L2Uyb0RvYy54bWxQSwECLQAUAAYACAAAACEA2E81+NwAAAAJAQAADwAAAAAAAAAAAAAAAADBBAAA&#xA;ZHJzL2Rvd25yZXYueG1sUEsFBgAAAAAEAAQA8wAAAMoFAAAAAA==&#xA;' stroked='f' strokeweight='.5pt'>");
				out.println ("              <v:textbox>");
				out.println ("                <w:txbxContent>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='00C854CA' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:pPr>");
				out.println ("                      <w:pStyle w:val='Address2'/>");
				out.println ("                      <w:ind w:right='720'/>");
				out.println ("                      <w:jc w:val='right'/>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:ascii='新細明體' w:fareast='新細明體' w:h-ansi='新細明體'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:b w:val='off'/>");
				out.println ("                        <w:sz w:val='36'/>");
				out.println ("                        <w:sz-cs w:val='36'/>");
				out.println ("                        <w:lang w:fareast='ZH-TW'/>");
				out.println ("                      </w:rPr>");
				out.println ("                    </w:pPr>");
				out.println ("                    <w:r wsp:rsidRPr='00434FB7'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:ascii='新細明體' w:fareast='新細明體' w:h-ansi='新細明體' w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:b w:val='off'/>");
				out.println ("                        <w:sz w:val='36'/>");
				out.println ("                        <w:sz-cs w:val='36'/>");
				out.println ("                        <w:lang w:fareast='ZH-TW'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>"+list.get(i).get("curr_post")+list.get(i).get("curr_addr")+"</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                </w:txbxContent>");
				out.println ("              </v:textbox>");
				out.println ("            </v:shape>");
				out.println ("          </w:pict>");
				out.println ("        </w:r>");
				out.println ("        <w:r>");
				out.println ("          <w:rPr>");
				out.println ("            <w:noProof/>");
				out.println ("          </w:rPr>");
				out.println ("          <w:pict>");
				out.println ("            <v:shape id='文字方塊 3' o:spid='_x0000_s1029' type='#_x0000_t202' style='position:absolute;margin-left:-18pt;margin-top:75.75pt;width:436.5pt;height:45.75pt;z-index:3;visibility:visible;mso-wrap-style:square;mso-width-percent:0;mso-wrap-distance-left:9pt;mso-wrap-distance-top:0;mso-wrap-distance-right:9pt;mso-wrap-distance-bottom:0;mso-position-horizontal:absolute;mso-position-horizontal-relative:text;mso-position-vertical:absolute;mso-position-vertical-relative:text;mso-width-percent:0;mso-width-relative:margin;v-text-anchor:top' o:gfxdata='UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF&#xA;90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA&#xA;0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD&#xA;OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893&#xA;SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y&#xA;JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl&#xA;bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR&#xA;JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY&#xA;22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i&#xA;OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA&#xA;IQDkzW33aQIAAKMEAAAOAAAAZHJzL2Uyb0RvYy54bWysVEtu2zAQ3RfoHQjua/mnNBUsB64DFwWM&#xA;JIBTZE1TlC2A4rAkbcm9QIEeIFn3AD1AD5Sco0NKcty0q6JaUPPTDOfNG00u6lKSvTC2AJXSQa9P&#xA;iVAcskJtUvrpdvHmnBLrmMqYBCVSehCWXkxfv5pUOhFD2ILMhCGYRNmk0indOqeTKLJ8K0pme6CF&#xA;QmcOpmQOVbOJMsMqzF7KaNjvn0UVmEwb4MJatF42TjoN+fNccHed51Y4IlOKd3PhNOFc+zOaTliy&#xA;MUxvC95eg/3DLUpWKCx6THXJHCM7U/yRqiy4AQu563EoI8jzgovQA3Yz6L/oZrVlWoReEByrjzDZ&#xA;/5eWX+1vDCmylI4oUazEET3df3388fB0//Px+zcy8ghV2iYYuNIY6ur3UOOkO7tFo2+8zk3p39gS&#xA;QT9ifTjiK2pHOBrjeDyKY3Rx9MXng/4w9mmi56+1se6DgJJ4IaUG5xdgZfuldU1oF+KLWZBFtiik&#xA;DMrBzqUhe4ajRoZkUFEimXVoTOkiPG213z6TilQpPRvhvXwWBT5fU0oqbxGBRm19D0XTspdcva4D&#xA;eMMOjjVkB0TJQMM0q/miwFaWeI8bZpBa2D2ui7vGI5eAlaGVKNmC+fI3u4/HiaOXkgqpmlL7eceM&#xA;wPY+KuTCu8F47LkdlHH8doiKOfWsTz1qV84BIRrgYmoeRB/vZCfmBso73KqZr4oupjjWTqnrxLlr&#xA;Fgi3kovZLAQhmzVzS7XS3Kf2uPlB3dZ3zOh2mg55cAUdqVnyYqhNbDOD2c5BXoSJe5wbVJEpXsFN&#xA;CJxpt9av2qkeop7/LdNfAAAA//8DAFBLAwQUAAYACAAAACEAnZUtid4AAAALAQAADwAAAGRycy9k&#xA;b3ducmV2LnhtbEyPwW7CMBBE75X6D9ZW6g2cEKAoxEFVpV4rFShnEy9x1Hgd2QYCX9/tqT3uzGj2&#xA;TbUZXS8uGGLnSUE+zUAgNd501CrY794nKxAxaTK694QKbhhhUz8+VLo0/kqfeNmmVnAJxVIrsCkN&#xA;pZSxseh0nPoBib2TD04nPkMrTdBXLne9nGXZUjrdEX+wesA3i8339uwUHFp3P3zlQ7DG9XP6uN92&#xA;e98p9fw0vq5BJBzTXxh+8RkdamY6+jOZKHoFk2LJWxIbi3wBghOr4oWVo4LZvMhA1pX8v6H+AQAA&#xA;//8DAFBLAQItABQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVu&#xA;dF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhADj9If/WAAAAlAEAAAsAAAAAAAAAAAAAAAAALwEA&#xA;AF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAOTNbfdpAgAAowQAAA4AAAAAAAAAAAAAAAAALgIA&#xA;AGRycy9lMm9Eb2MueG1sUEsBAi0AFAAGAAgAAAAhAJ2VLYneAAAACwEAAA8AAAAAAAAAAAAAAAAA&#xA;wwQAAGRycy9kb3ducmV2LnhtbFBLBQYAAAAABAAEAPMAAADOBQAAAAA=&#xA;' stroked='f' strokeweight='.5pt'>");
				out.println ("              <v:textbox>");
				out.println ("                <w:txbxContent>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='00C854CA' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:pPr>");
				out.println ("                      <w:jc w:val='center'/>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:sz w:val='48'/>");
				out.println ("                        <w:sz-cs w:val='48'/>");
				out.println ("                      </w:rPr>");
				out.println ("                    </w:pPr>");
				out.println ("                    <w:r wsp:rsidRPr='00C854CA'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:sz w:val='48'/>");
				out.println ("                        <w:sz-cs w:val='48'/>");
				out.println ("                      </w:rPr>");
				try{
					out.println ("                      <w:t>"+list.get(i).get("parent_name")+" 家長收</w:t>");					
				}catch(Exception e){
					out.println ("                      <w:t>"+list.get(i).get("student_name")+" 同學收</w:t>");
				}			
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                </w:txbxContent>");
				out.println ("              </v:textbox>");
				out.println ("            </v:shape>");
				out.println ("          </w:pict>");
				out.println ("        </w:r>");
				out.println ("        <w:r>");
				out.println ("          <w:rPr>");
				out.println ("            <w:noProof/>");
				out.println ("          </w:rPr>");
				out.println ("          <w:pict>");
				out.println ("            <v:shape id='文字方塊 1' o:spid='_x0000_s1028' type='#_x0000_t202' style='position:absolute;margin-left:-25.5pt;margin-top:0;width:204pt;height:43.5pt;z-index:1;visibility:visible;mso-wrap-style:square;mso-height-percent:0;mso-wrap-distance-left:9pt;mso-wrap-distance-top:0;mso-wrap-distance-right:9pt;mso-wrap-distance-bottom:0;mso-position-horizontal:absolute;mso-position-horizontal-relative:text;mso-position-vertical:absolute;mso-position-vertical-relative:text;mso-height-percent:0;mso-height-relative:margin;v-text-anchor:top' o:gfxdata='UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF&#xA;90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA&#xA;0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD&#xA;OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893&#xA;SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y&#xA;JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl&#xA;bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR&#xA;JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY&#xA;22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i&#xA;OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA&#xA;IQDW2C+xZgIAAJwEAAAOAAAAZHJzL2Uyb0RvYy54bWysVE1uEzEU3iNxB8t7OklISht1UoVWQUgV&#xA;rdSirh2PpxnJ42dsJzPhAkgcoKw5AAfgQO05+OyZtKWwQmThvL+8n+97L0fHba3ZRjlfkcn5cG/A&#xA;mTKSisrc5Pzj1eLVAWc+CFMITUblfKs8P569fHHU2Kka0Yp0oRxDEuOnjc35KgQ7zTIvV6oWfo+s&#xA;MnCW5GoRoLqbrHCiQfZaZ6PBYD9ryBXWkVTew3raOfks5S9LJcN5WXoVmM45egvpdeldxjebHYnp&#xA;jRN2Vcm+DfEPXdSiMij6kOpUBMHWrvojVV1JR57KsCepzqgsK6nSDJhmOHg2zeVKWJVmATjePsDk&#xA;/19a+WFz4VhVgDvOjKhB0f3tl7sf3+5vf959/8qGEaHG+ikCLy1CQ/uW2hjd2z2McfC2dHX8xkgM&#xA;fmC9fcBXtYFJGEeTw8HBAC4J32QyGk8SAdnjr63z4Z2imkUh5w78JVjF5swHVEToLiQW86SrYlFp&#xA;nZStP9GObQSoxoYU1HCmhQ8w5nyRPrFppPjtZ9qwJuf7r9FLzGIo5uvitIkWldaorx+h6EaOUmiX&#xA;bY/Dkoot4HHUrZi3clFhhjM0cCEcdgpj407COZ5SE0pSL3G2Ivf5b/YYD6rh5azBjubcf1oLpzDX&#xA;e4MlOByOx3GpkzKevBlBcU89y6ces65PCNiAaHSXxBgf9E4sHdXXOKd5rAqXMBK1cx524knoLgfn&#xA;KNV8noKwxlaEM3NpZUwdAYsMXbXXwtmexoAF+EC7bRbTZ2x2sR3483WgskpUR4A7VEFaVHACib7+&#xA;XOONPdVT1OOfyuwXAAAA//8DAFBLAwQUAAYACAAAACEAydkTMNoAAAAHAQAADwAAAGRycy9kb3du&#xA;cmV2LnhtbEyPT0/DMAzF70h8h8hI3La0wGAqdSeExBWJbeycNaapSJyqybZunx5zgov/6Fnv/Vyv&#xA;puDVkcbUR0Yo5wUo4jbanjuE7eZttgSVsmFrfGRCOFOCVXN9VZvKxhN/0HGdOyUmnCqD4HIeKq1T&#xA;6yiYNI8DsWhfcQwmyzp22o7mJObB67uieNTB9CwJzgz06qj9Xh8Cwq4Ll91nOYzOBv/A75fzZht7&#xA;xNub6eUZVKYp/x3DL76gQyNM+3hgm5RHmC1K+SUjSBX5fvEkwx5hKV03tf7P3/wAAAD//wMAUEsB&#xA;Ai0AFAAGAAgAAAAhALaDOJL+AAAA4QEAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVz&#xA;XS54bWxQSwECLQAUAAYACAAAACEAOP0h/9YAAACUAQAACwAAAAAAAAAAAAAAAAAvAQAAX3JlbHMv&#xA;LnJlbHNQSwECLQAUAAYACAAAACEA1tgvsWYCAACcBAAADgAAAAAAAAAAAAAAAAAuAgAAZHJzL2Uy&#xA;b0RvYy54bWxQSwECLQAUAAYACAAAACEAydkTMNoAAAAHAQAADwAAAAAAAAAAAAAAAADABAAAZHJz&#xA;L2Rvd25yZXYueG1sUEsFBgAAAAAEAAQA8wAAAMcFAAAAAA==&#xA;' stroked='f' strokeweight='.5pt'>");
				out.println ("              <v:textbox>");
				out.println ("                <w:txbxContent>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='00C854CA' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:pPr>");
				out.println ("                      <w:pStyle w:val='Address1'/>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:ascii='新細明體' w:fareast='新細明體' w:h-ansi='新細明體'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:color w:val='003300'/>");
				out.println ("                        <w:sz w:val='24'/>");
				out.println ("                      </w:rPr>");
				out.println ("                    </w:pPr>");
				out.println ("                    <w:r wsp:rsidRPr='00C854CA'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:ascii='新細明體' w:fareast='新細明體' w:h-ansi='新細明體'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:color w:val='003300'/>");
				out.println ("                        <w:sz w:val='24'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>中華科技大學</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='00C854CA' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:pPr>");
				out.println ("                      <w:pStyle w:val='Address1'/>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:ascii='新細明體' w:fareast='新細明體' w:h-ansi='新細明體'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:lang w:fareast='ZH-TW'/>");
				out.println ("                      </w:rPr>");
				out.println ("                    </w:pPr>");
				out.println ("                    <w:r>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:ascii='新細明體' w:fareast='新細明體' w:h-ansi='新細明體' w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:lang w:fareast='ZH-TW'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>11581</w:t>");
				out.println ("                    </w:r>");
				out.println ("                    <w:r>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:ascii='新細明體' w:fareast='新細明體' w:h-ansi='新細明體'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>台北市南港區研究院路三段245號</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                </w:txbxContent>");
				out.println ("              </v:textbox>");
				out.println ("            </v:shape>");
				out.println ("          </w:pict>");
				out.println ("        </w:r>");
				out.println ("        <w:r>");
				out.println ("          <w:rPr>");
				out.println ("            <w:noProof/>");
				out.println ("          </w:rPr>");
				out.println ("          <w:pict>");
				out.println ("            <v:shape id='文字方塊 2' o:spid='_x0000_s1027' type='#_x0000_t202' style='position:absolute;margin-left:312pt;margin-top:-.75pt;width:120pt;height:61.5pt;z-index:2;visibility:visible;mso-wrap-style:square;mso-height-percent:0;mso-wrap-distance-left:9pt;mso-wrap-distance-top:0;mso-wrap-distance-right:9pt;mso-wrap-distance-bottom:0;mso-position-horizontal:absolute;mso-position-horizontal-relative:text;mso-position-vertical:absolute;mso-position-vertical-relative:text;mso-height-percent:0;mso-height-relative:margin;v-text-anchor:top' o:gfxdata='UEsDBBQABgAIAAAAIQC2gziS/gAAAOEBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRQU7DMBBF&#xA;90jcwfIWJU67QAgl6YK0S0CoHGBkTxKLZGx5TGhvj5O2G0SRWNoz/78nu9wcxkFMGNg6quQqL6RA&#xA;0s5Y6ir5vt9lD1JwBDIwOMJKHpHlpr69KfdHjyxSmriSfYz+USnWPY7AufNIadK6MEJMx9ApD/oD&#xA;OlTrorhX2lFEilmcO2RdNtjC5xDF9pCuTyYBB5bi6bQ4syoJ3g9WQ0ymaiLzg5KdCXlKLjvcW893&#xA;SUOqXwnz5DrgnHtJTxOsQfEKIT7DmDSUCaxw7Rqn8787ZsmRM9e2VmPeBN4uqYvTtW7jvijg9N/y&#xA;JsXecLq0q+WD6m8AAAD//wMAUEsDBBQABgAIAAAAIQA4/SH/1gAAAJQBAAALAAAAX3JlbHMvLnJl&#xA;bHOkkMFqwzAMhu+DvYPRfXGawxijTi+j0GvpHsDYimMaW0Yy2fr2M4PBMnrbUb/Q94l/f/hMi1qR&#xA;JVI2sOt6UJgd+ZiDgffL8ekFlFSbvV0oo4EbChzGx4f9GRdb25HMsYhqlCwG5lrLq9biZkxWOiqY&#xA;22YiTra2kYMu1l1tQD30/bPm3wwYN0x18gb45AdQl1tp5j/sFB2T0FQ7R0nTNEV3j6o9feQzro1i&#xA;OWA14Fm+Q8a1a8+Bvu/d/dMb2JY5uiPbhG/ktn4cqGU/er3pcvwCAAD//wMAUEsDBBQABgAIAAAA&#xA;IQBsAIsvcwIAAMsEAAAOAAAAZHJzL2Uyb0RvYy54bWysVEtuGzEM3RfoHQTtmxm7zqdGxoGbwEWB&#xA;IAmQFFnLGk08qEZUJdkz7gUK5ADpugfoAXqg5Bx9kj9Jk66KeiGTIvVIPpJzeNQ1mi2U8zWZgvd2&#xA;cs6UkVTW5qbgn64mbw4480GYUmgyquBL5fnR6PWrw9YOVZ9mpEvlGECMH7a24LMQ7DDLvJypRvgd&#xA;ssrAWJFrRIDqbrLSiRbojc76eb6XteRK60gq73F7sjLyUcKvKiXDeVV5FZguOHIL6XTpnMYzGx2K&#xA;4Y0TdlbLdRriH7JoRG0QdAt1IoJgc1e/gGpq6chTFXYkNRlVVS1VqgHV9PJn1VzOhFWpFpDj7ZYm&#xA;//9g5dniwrG6LHifMyMatOjh7tv9z+8Pd7/uf9yyfmSotX4Ix0sL19C9pw6d3tx7XMbCu8o18R8l&#xA;MdjB9XLLr+oCk/HRbn+Q5zBJ2PYPevluakD2+No6Hz4oalgUCu7Qv0SrWJz6gEzgunGJwTzpupzU&#xA;Widl6Y+1YwuBVmNCSmo508IHXBZ8kn4xaUD88Uwb1hZ87y1yeQEZY20xp1rIzy8RgKdNfKnSuK3z&#xA;jJStqIlS6KZdInlL25TKJdh0tJpIb+WkRrBT5HshHEYQLGGtwjmOShMypLXE2Yzc17/dR39MBqyc&#xA;tRjpgvsvc+EUaPhoMDPveoNB3IGkDHb3+1DcU8v0qcXMm2MClT0ssJVJjP5Bb8TKUXON7RvHqDAJ&#xA;IxG74GEjHofVomF7pRqPkxOm3opwai6tjNCRt0jyVXctnF13PWBezmgz/GL4rPkr3/jS0HgeqKrT&#xA;ZESeV6yix1HBxqRur7c7ruRTPXk9foNGvwEAAP//AwBQSwMEFAAGAAgAAAAhALqeDfvcAAAACgEA&#xA;AA8AAABkcnMvZG93bnJldi54bWxMjz1PwzAQhnck/oN1ldhapylEVYhTARISYqPNwubG1ySqfY5s&#xA;twn/nusE47336P2odrOz4oohDp4UrFcZCKTWm4E6Bc3hfbkFEZMmo60nVPCDEXb1/V2lS+Mn+sLr&#xA;PnWCTSiWWkGf0lhKGdsenY4rPyLx7+SD04nP0EkT9MTmzso8ywrp9ECc0OsR33psz/uLU/BRvKZv&#xA;bMyn2eQbPzWyDScblXpYzC/PIBLO6Q+GW32uDjV3OvoLmSisgiJ/5C1JwXL9BIKBbXETjkzmrMi6&#xA;kv8n1L8AAAD//wMAUEsBAi0AFAAGAAgAAAAhALaDOJL+AAAA4QEAABMAAAAAAAAAAAAAAAAAAAAA&#xA;AFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAOP0h/9YAAACUAQAACwAAAAAAAAAA&#xA;AAAAAAAvAQAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEAbACLL3MCAADLBAAADgAAAAAAAAAA&#xA;AAAAAAAuAgAAZHJzL2Uyb0RvYy54bWxQSwECLQAUAAYACAAAACEAup4N+9wAAAAKAQAADwAAAAAA&#xA;AAAAAAAAAADNBAAAZHJzL2Rvd25yZXYueG1sUEsFBgAAAAAEAAQA8wAAANYFAAAAAA==&#xA;' strokeweight='.5pt'>");
				out.println ("              <v:textbox>");
				out.println ("                <w:txbxContent>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='006A70F8' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:pPr>");
				out.println ("                      <w:jc w:val='distribute'/>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:sz-cs w:val='24'/>");
				out.println ("                      </w:rPr>");
				out.println ("                    </w:pPr>");
				out.println ("                    <w:r wsp:rsidRPr='006A70F8'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:sz-cs w:val='24'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>國內郵資已付</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='006A70F8' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:pPr>");
				out.println ("                      <w:jc w:val='distribute'/>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:sz-cs w:val='24'/>");
				out.println ("                      </w:rPr>");
				out.println ("                    </w:pPr>");
				out.println ("                    <w:r wsp:rsidRPr='006A70F8'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:sz-cs w:val='24'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>北區營收許可證</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:pPr>");
				out.println ("                      <w:jc w:val='distribute'/>");
				out.println ("                    </w:pPr>");
				out.println ("                    <w:r wsp:rsidRPr='006A70F8'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                        <w:sz-cs w:val='24'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>北台字第17573號</w:t>");
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
				out.println ("                </w:txbxContent>");
				out.println ("              </v:textbox>");
				out.println ("            </v:shape>");
				out.println ("          </w:pict>");
				out.println ("        </w:r>");
				out.println ("      </w:p>");
				
				out.println("    <w:br w:type='page'/>");			
				
			}			
			
			for(int i=0; i<list.size(); i++){
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>"+list.get(i).get("parent_name")+" "+list.get(i).get("curr_post")+list.get(i).get("curr_addr")+"</w:t>");			
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
			}
			out.println("    <w:br w:type='page'/>");
			
			for(int i=0; i<list.size(); i++){
				out.println ("                  <w:p wsp:rsidR='00C854CA' wsp:rsidRPr='000B302C' wsp:rsidRDefault='00C854CA' wsp:rsidP='00C854CA'>");
				out.println ("                    <w:r wsp:rsidRPr='000B302C'>");
				out.println ("                      <w:rPr>");
				out.println ("                        <w:rFonts w:hint='fareast'/>");
				out.println ("                        <wx:font wx:val='新細明體'/>");
				out.println ("                      </w:rPr>");
				out.println ("                      <w:t>"+list.get(i).get("student_no")+" "+list.get(i).get("student_name")+" "+list.get(i).get("parent_name")+" 缺曠"+list.get(i).get("endCnt")+"節</w:t>");			
				out.println ("                    </w:r>");
				out.println ("                  </w:p>");
			}
			
			out.println ("      <w:sectPr wsp:rsidR='007A476C' wsp:rsidRPr='00C854CA'>");
			out.println ("        <w:pgSz w:w='11906' w:h='16838'/>");
			out.println ("        <w:pgMar w:top='1440' w:right='1800' w:bottom='1440' w:left='1800' w:header='851' w:footer='992' w:gutter='0'/>");
			out.println ("        <w:cols w:space='425'/>");
			out.println ("        <w:docGrid w:type='lines' w:line-pitch='360'/>");
			out.println ("      </w:sectPr>");
			out.println ("    </wx:sect>");
			out.println ("  </w:body>");
			out.println ("</w:wordDocument>");
			out.close();			
	}
}